name: Scan AGL Image

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build-yocto:
    name: Build & Scan AGL Image
    runs-on: [self-hosted, yocto-demo-runner-1]
  
    steps:
      - name: Checkout AGL Demo branch
        uses: actions/checkout@v4
        with:
          path: corefense-agl-demo
          ref: test

      - uses: ./corefense-agl-demo/.github/actions/prepare-agl-build
      
      - name: Run Core-Agent
        uses: ./corefense-agl-demo/.github/actions/run-core-agent
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          JOB_ID: ${{ github.run_id }}
          BUILD_DIR: $GITHUB_WORKSPACE/demo/AGL/qemux86-64
          CORE_AGENT_BIN: $GITHUB_WORKSPACE/demo/AGL/qemux86-64/core-agent
          TARGET_IMAGE: agl-image-minimal
